name = "one-msg-board"
compatibility_date = "2024-01-01"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "one_msg_board"
database_id = "$DATABASE_ID"

# R2 存储绑定
[[r2_buckets]]
binding = "R2"
bucket_name = "$R2_BUCKET_NAME"

[build]
command = "yarn build"
output_directory = ".next"

[site]
bucket = ".next"
entry-point = "."

[env.production]
NODE_ENV = "production"
SESSION_SECRET = "$SESSION_SECRET"
R2_ACCOUNT_ID = "$R2_ACCOUNT_ID"
R2_ACCESS_KEY_ID = "$R2_ACCESS_KEY_ID"
R2_SECRET_ACCESS_KEY = "$R2_SECRET_ACCESS_KEY"
R2_PUBLIC_URL = "$R2_PUBLIC_URL"

[env.development]
NODE_ENV = "development"
SESSION_SECRET = "$SESSION_SECRET"
R2_ACCOUNT_ID = "$R2_ACCOUNT_ID"
R2_ACCESS_KEY_ID = "$R2_ACCESS_KEY_ID"
R2_SECRET_ACCESS_KEY = "$R2_SECRET_ACCESS_KEY"
R2_PUBLIC_URL = "$R2_PUBLIC_URL" 